apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
spec: 
  ingressClassName: {{ .Values.deployment.ingress.ClassName }}
  rules:
    - http:
        paths:
          - path: {{ .Values.deployment.ingress.path }}
            pathType: {{ .Values.deployment.ingress.pathType }}
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name .Values.deployment.service }}
                port: 
                  number: {{ .Values.deployment.containerPort}}

